### ISSUE TITLE
Feature suggestion: Random Date

### ISSUE THREAD

**Issue by Hyzual** [kimpettersen/random-sublime-text-plugin#18]
Hi !

Love this plugin, I use it all the time to generate fake unit-test data.
Sometimes, I deal with dates and would love the ability to generate a random ISO-8601 formatted date.

**Comment by natharduini** [comment]
It would be very useful indeed.
"Random int" could have been an acceptable workaround but you can't have the zero-padded numbers (as in 2015-06-05)...

**Comment by kimpettersen** [comment]
Thanks for the suggestion. This seems to be the most requested feature for this plugin, so I'll try to get to it ASAP.

**Comment by kimpettersen** [comment]
@Hyzual @natharduini Added date parsing and fixed a bug with generating email addressed!

Hope this works for you and thanks for using the plugin and giving feedback

**Comment by Hyzual** [comment]
Thanks for the quick addition, the date generator is what I was looking for !

**Comment by natharduini** [comment]
Excellent, thank you.

**Comment by howar31** [comment]
Hi @kimpettersen ,

Thanks for adding random date.  Would you add random "time" and "datetime" as well?

i.g.

- Random Time:  01;34:59
- Random DateTime: 2017-01-25 13:41:32

Thank you

**Comment by kimpettersen** [comment]
Hi @howar31,

Good idea, but it is unlikely that I'll be doing this in the near future. Feel free to submit a PR though

**Comment by howar31** [comment]
Cool! 
I have no experience with Sublime Text plugin.  But I'll try it at my free time.  :D
